### ISSUE TITLE
1.1.2 凑零钱问题 | Computer Cookbook School Recruitment

### ISSUE THREAD

**Issue by graysonwp** [graysonwp/ComputerCookbook-SchoolRecruitment#2]
https://school-recruitment.grayson.top/public/docs/algorithm/1%E7%AE%97%E6%B3%95%E6%A1%86%E6%9E%B6/1.1-%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92/1.1.2-%E5%87%91%E9%9B%B6%E9%92%B1%E9%97%AE%E9%A2%98/

**Comment by wpwbb510582246** [comment]
测试
